# Numpy Cheat Sheet

The NumPy library is the core library for scientific computing in Python. It provides a  high-performance multidimensional array object, and tools for working with these arrays.  

In [1]:
import numpy as np

## Properties of a numpy array

- They must be homogenous
- They are of fixed size
- The dimensions are known at creation time


In [4]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [8]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

## Initialization

You can create arrays with initial placeholder values with the following methods.

In [11]:
# Initialize a numpy array with zeros
# data type is float by default
# 3 rows and 4 columns
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
# Initialize a numpy array with ones
# 2 rows and 3 columns
# dtype can be specified
np.ones((2, 3), dtype = np.int16)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [13]:
# Create an array of evenly spaced values (step value)
# Start at 10, end at 100, step by 15
np.arange(10, 100, 15)

array([10, 25, 40, 55, 70, 85])